[package]
name = "calc-engine"
version = "0.1.0"
authors = ["Illia Dekhtiarenko <illya.dekhtyarenko@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
